version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.9.27-management
        container_name: rabbitmq
        volumes:
            - $PWD/data/:/var/lib/rabbitmq/mnesia
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
        ports:
            - "5672:5672"
            - "15672:15672"


#  Crear las carpetas de  mkdir rabbitmq
#  Dar permisos a las carpetas chmod a+rwx -R rabbitmq/data